# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.1.4"

package:
  name: vizro-mcp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/v/vizro-mcp/vizro_mcp-${{ version }}.tar.gz
  sha256: b5f819c6c97cb73a7c3ec237d5bb7d5a042371d5e6a013025523834ea8d9b765

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - vizro-mcp = vizro_mcp:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic
    - httpx >=0.28.1
    - mcp >=1.6.0
    - vizro >=0.1.46
    - click >=8.1.7
    # Refer to https://github.com/mckinsey/vizro/blob/main/vizro-mcp/pyproject.toml#L21
    # "pandas[html,parquet,excel]"
    - pandas
    # Refer to https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L68
    # html = ['beautifulsoup4>=4.12.3', 'html5lib>=1.1', 'lxml>=4.9.2']
    - beautifulsoup4 >=4.12.3
    - html5lib >=1.1
    - lxml >=4.9.2
    # excel = ['odfpy>=1.4.1', 'openpyxl>=3.1.2', 'python-calamine>=0.1.7', 'pyxlsb>=1.0.10', 'xlrd>=2.0.1', 'xlsxwriter>=3.2.0']
    - odfpy >=1.4.1
    - openpyxl >=3.1.2
    - python-calamine >=0.1.7
    - pyxlsb >=1.0.10
    - xlrd >=2.0.1
    - xlsxwriter >=3.2.0
    # parquet = ['pyarrow>=10.0.1']
    - pyarrow >=10.0.1

tests:
  - python:
      imports:
        - vizro_mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python
    script:
      - vizro-mcp --help

about:
  summary: MCP server to help create Vizro dashboards and charts
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/vizro-mcp/
  description: Vizro-MCP is a Python library that provides a server to help create Vizro dashboards and charts.
  repository: https://github.com/mckinsey/vizro
  documentation: https://vizro.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - rxm7706
